title: "Kandra.ID"
author: "Kandra Wilko"
email: "halo@kandra.id"
description: "Kandra Wilko Blog on Github"
baseurl: "/blog-template"
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
